### ISSUE TITLE
Analysis workflow bug

### ISSUE THREAD

**Issue by jon-stokes** [validmeasures/wash#10] opened 2017-12-12 20:16 UTC
We are encountering a bug in the updated analysis workflow (see attached) in Step 4c where results are being combined. It looks like a simple naming error issue, but we're not sure how to resolve.

## `Analysis workflow bug` screenshot
<img width="1278" alt="workflow bug 121217" src="https://user-images.githubusercontent.com/33328249/33906065-a8668732-df78-11e7-99d4-cd104a3ed520.png">

Thanks - Jonathan

**Comment by ernestguevarra** [comment] 2017-12-13 06:17
This is not a bug. When you run the analysis, you skipped the node for classification so no data frame results for classification results are found in the `outputTables` folder. Without this data frame results, the concatenation node will not work because it can't find the file containing the classification results.

It is required that the classification analysis be done alongside the estimation analysis. It only takes less than a minute to run so there is no waste of your time.

**Comment by jon-stokes** [comment] 2017-12-13 12:54
We actually did run the classification node. I ran the workflow again this morning to double-check and encountered the same error message. Attached is a screenshot of the `outputTables` folder generated this morning, showing that other classifications were generated but not classifications by corporation.

<img width="924" alt="screen shot 2017-12-13 at 12 45 29" src="https://user-images.githubusercontent.com/33328249/33939854-a182e9d8-e004-11e7-86c5-5cff86064002.png">

**Comment by ernestguevarra** [comment] 2017-12-13 13:10
Did you run the `Classify by corporation` node (see screenshot below)? 

![rflowclassifynodewsup](https://user-images.githubusercontent.com/5742010/33940473-046ff2be-e007-11e7-9684-bd9aeb369319.png)

It is found inside the `Classify` node but will not be run automatically as it is a sidewards branch of the boxed node. I did it this way because the classify by corporation is specific to Bangladesh. This node will only work for Bangladesh. If we didn't do it this way, errors will keep coming out when you analyse your data from other cities.

In your `outputTables` folder, no corporation results are shown (both for classification and estimation). This is because you haven't run the corporation node for both classification and estimation. Drill down on the classification and estimation node and then run the `Classify by corporation` and `Estimate by corporation` node separately. Do this by selecting the corresponding corporation node and then applying `CTRL` + `SHIFT` + `R` to run the whole line of code for estimation but specific to the corporation. 

Let me know if this is clear.

**Comment by jon-stokes** [comment] 2017-12-14 10:03
Thanks @ernestguevarra - I didn't realise this needed to be run manually but I see why this needs to be the case. We ran everything again last night/this morning, running `Classify` (all default nodes), then `Classify by Corporation`, then `Estimate` (all default nodes) and then `Estimate by Corporation` with no problems.

**Comment by ernestguevarra** [comment] 2017-12-15 11:58
Good. I will close this now. Feel free to open it again if you think still not resolved. Just to say that in the README.md file that shows up when you go this repository, it specifically states there that you have to run the corporation node separately. So, our documentation covers that.

**Closed by ernestguevarra** 2017-12-15 11:58 UTC
Labels: bug, not an issue
